# on Windows -- $env:SKIP="tests,example"
repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: python3 -m ruff check core/ utils/ views/ main.py config.py mapping.py tests/ --fix
        language: system
        always_run: true
        pass_filenames: false
      - id: tests
        name: tests
        entry: env PYTHONPATH="." python3 -m pytest tests/
        language: system
        always_run: true
        pass_filenames: false
      - id: pylint
        name: pylint
        entry: python3 -m pylint core/ utils/ views/ main.py config.py mapping.py tests/
        language: system
        always_run: true
        pass_filenames: false