YOLO_WORLD_CLASSES = {
    "Coffee cup lid": "Small plastic lid",
    "Bottle cap": "Plastic bottle cap",
    "PS styrofoam": "Polystyrene foam",
    "Light blue pet bottle": "Light blue PET bottle",
    "Clear pet bottle food covered": "Clear PET food bottle",
    "Clear pet bottle non food convered": "Clear PET non-food bottle",
    "Clear pet bottle": "Transparent PET bottle",
    "Brown pet bottle": "Brown PET bottle",
    "Coloured pet bottle": "Colored PET bottle",
    "Dark blue pet bottle": "Dark blue PET bottle",
    "Green pet bottle": "Green PET bottle",
    "White pet bottle": "White PET bottle",
    "Pet bottle other colour": "Colored PET bottle",
    "Coloured hdpe bottle": "Colored HDPE bottle",
    "Coloured yoghurt plastic bottle": "Colored yogurt bottle",
    "Coloured hdpe bottle": "Colored HDPE bottle",
    "Natural hdpe bottle": "Natural HDPE bottle",
    "Natural yoghurt plastic bottle": "Natural yogurt bottle",
    "Natural hdpe bottle": "Natural HDPE bottle",
    "Black container": "Black plastic container",
    "Black plastic bottle": "Black plastic bottle",
    "Other black plastic": "Black plastic items",
    "Clear container": "Clear plastic container",
    "Coloured container": "Colored plastic container",
    "White container": "White plastic container",
    "Other plastic": "Miscellaneous plastics",
    "Bottle label film": "Labeling plastic film",
    "Film bubble wrap": "Bubble wrap film",
    "Clear film": "Transparent plastic film",
    "Clear printed film": "Printed clear film",
    "Coloured film": "Colored plastic film",
    "Filled bag": "Filled plastic bag",
    "Coloured printed film": "Colored printed film",
    "Metallised film": "Metalized plastic film",
    "Black film": "Black plastic film",
    "Aluminium Aerosol": "Aluminum aerosol cans",
    "Aluminium cans": "Aluminum beverage cans",
    "Aluminium other": "Aluminum materials",
    "Steel cans": "Steel cans",
    "Metal other": "Miscellaneous metals",
    "Cardboard packaging": "Cardboard boxes",
    "Paper packaging": "Paper packaging",
    "Clean paper sheet (Can be written on, but no food)": "Clean paper sheets",
    "Dirty paper (Food, etc.)": "Contaminated paper",
    "Wipes": "Disposable wipes",
    "Tetra Pak Carton (Milk, juice cartons, etc.)": "Tetra Pak cartons",
    "Cup drink (Disposable cups)": "Disposable drink cups",
    "Cup food (Disposable food containers)": "Disposable food containers",
    "Weee (Waste Electrical and Electronic Equipment)": "Electronic waste",
    "Batteries": "Batteries",
    "Clear glass bottle": "Clear glass bottles",
    "Green glass bottle": "Green glass bottles",
    "Brown glass bottle": "Brown glass bottles",
    "Clear glass cullet (broken)": "Broken clear glass",
    "Green glass cullet (broken)": "Broken green glass",
    "Brown glass cullet (broken)": "Broken brown glass",
    "Glass with plastic": "Glass mixed with plastic",
    "Other glass": "Miscellaneous glass",
    "Clothes/Fabric": "Clothing and textiles",
    "Fine (small granular material)": "Fine granular waste",
    "Sanitary": "Sanitary waste",
    "Other (General waste)": "General miscellaneous waste"
}
