name: Lint

on:
  pull_request:
    branches: [ main ]  # or master, depending on your default branch
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # adjust version as needed

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libpulse-mainloop-glib0 \
            libgstreamer1.0-0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly \
            gstreamer1.0-libav \
            libqt5multimedia5-plugins \
            libqt5multimedia5 \
            libqt5multimediagsttools5 \
            libqt5multimediawidgets5 \
            qtmultimedia5-dev

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pylint pytest PyQt5 opencv-python

      - name: Run Ruff
        run: python -m ruff check core/ utils/ views/ main.py config.py mapping.py tests/ --fix

      - name: Run Tests
        env:
          PYTHONPATH: "."
          QT_QPA_PLATFORM: "offscreen"
        run: python -m pytest tests/

      - name: Run Pylint
        run: python -m pylint core/ utils/ views/ main.py config.py mapping.py tests/